2025-01-18 11:12:49,052 | INFO | "test_challenge" выполнен успешно
2025-01-18 11:12:49,052 | WARNING | Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int
2025-01-18 11:12:49,053 | WARNING | Traceback (most recent call last):
  File "C:\Python\My_project\tests_12_4.py", line 83, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "C:\Python\My_project\tests_12_4.py", line 15, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2025-01-18 11:12:49,053 | WARNING | Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5
2025-01-18 11:12:49,055 | WARNING | Traceback (most recent call last):
  File "C:\Python\My_project\tests_12_4.py", line 72, in test_walk
    runner = Runner("Вася", -5)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Python\My_project\tests_12_4.py", line 20, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

